### ISSUE TITLE
How can I show tool tip when I hover over a palace

### ISSUE THREAD

**Issue by usama-asfar** [South-Paw/react-vector-maps#19]
![Screenshot from 2019-11-08 22-24-32](https://user-images.githubusercontent.com/42825498/68495616-93f62500-0276-11ea-9b59-1243f1ee56d9.png)

**Comment by South-Paw** [comment]
Hi there since this is not an issue or bug with the component I'm closing the issue.

You need to spend some of your own time investigating how to make tooltips and then combine it with this library - you can find examples out on the web of how to make tooltips on hover and then combine it with React events to get the desired results.

There is an [old example here](https://github.com/South-Paw/react-vector-maps/blob/3b66cd47de0a28df040fdbdb6000c66b25547906/src/examples/TooltipLayers.js) but this has a few issues with it (I also don't intend to provide support if you choose to copy it)
