### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by cquex** [South-Paw/react-vector-maps#21]
Hi! Is there a way to put a tooltip with the name of the region ?

**Comment by South-Paw** [comment]
Hi :wave:

You can implement tooltips by attaching `onMouseOver`, `onMouseMove` and `onMouseOut` events to the layers via the `layerProps` prop. Here is some incomplete pseudo code for you from another project - the functions should be wrapped in hooks of course but hopefully you get the idea and can go from here.

```js
const MyComponent = () => {
  const onMouseOver = (event) => {
    // `event.target.attributes.id.value` is the id of the layer you just mouse over'ed
  }

  const onMouseMove = (event) => {
    // `event.clientY` and `event.clientX` are the position the tooltip should be at
  }

  const onMouseOut = (event) => {
    // clear the current tooltip
  }

  return <VectorMap {...map} layerProps={{ onMouseOver, onMouseMove, onMouseOut }} >
}
```

And then you can use the `x` and `y` positions to position an absolute `div` on the map which contains the tooltip.

Since this is not an issue with the package I'm going to close it and mark as a question.
