### ISSUE TITLE
type of "layerProps"

### ISSUE THREAD

**Issue by CityHopper** [South-Paw/react-vector-maps#33]
"layerProps" is for event handlers, and the type was "any" before.
Why the type has been changed into "React.SVGProps<SVGPathElement>", and how do you apply for event handlers?

[Before] layerProps?: any;
[Current] layerProps?: React.SVGProps<SVGPathElement>;

The tutorial from the document doesn't work.

Many thanks.

**Comment by South-Paw** [comment]
> Why the type has been changed into "React.SVGProps"

Because if you actually care about the utilizing TypeScript that is the correct type to be used for where the props end up.

Having `any` is simply bad practice - if you want to use `any` you might as well just use ol' JavaScript because you're not utilizing TypeScript for it's literal purpose... types.

> how do you apply for event handlers?

The documentation is 'working' because it uses JavaScript in your browser.

You have to realize that the docs were written in 2019 when the package was only using JavaScript and when I updated things to TypeScript later in 2021 the docs weren't broken so didn't need fixing.

For now, here's an example of TypeScript usage of `layerProps`

```diff
const layerProps: VectorMapProps['layerProps'] = {
     // These two both work in a browser, but the second is correctly typed for TypeScript
-    onMouseEnter: ({ target }) => setHovered(target.attributes.name.value),
+    onMouseEnter: ({ currentTarget }) => setHovered(currentTarget.attributes.getNamedItem('name')?.value),
};
```

> The tutorial from the document doesn't work.

I agree that they are a little out of date, but I can't see any not working - which tutorial did you mean exactly?

**Comment by ilya-bkv** [comment]
In your example, TS gave an error: `Object is possibly 'null'`. In my case, I satisfied this code:

```js
const layerProps: VectorMapProps['layerProps'] = {
    onMouseEnter: ({ currentTarget }) => {
      const idAttribute = currentTarget.attributes.getNamedItem('id');
      if (idAttribute) {
        setSelected(idAttribute.value);
      }
    }
  }
```

Thank you for continuing to support the library!

**Comment by South-Paw** [comment]
Closing as haven't heard back and seems resolved. Will one day find time to update the examples 👍

**Comment by ilya-bkv** [comment]
Remember about object undefined: `setHovered(currentTarget.attributes.getNamedItem('name')?.value)` ¯\_(ツ)_/¯
